/**
 * THE SERVICE WORKER, BUILT FRESH EACH TIME IT IS ASKED FOR.
 *
 * A service worker is a small program the browser keeps running after the tab
 * is closed - it is the thing that can show an alert when nobody is looking at
 * the panel. It has to be served from the site's own address, which is why it
 * is a route here and not a file in `public/`.
 *
 * WHY IT IS GENERATED RATHER THAN WRITTEN OUT
 * A service worker cannot read the site's settings; whatever it needs has to
 * be inside it. Writing the Firebase values into a committed file would put a
 * SECOND copy of them in the project - and the day the first copy changes and
 * this one does not, alerts stop arriving and nothing anywhere says why.
 * So the settings are fetched from the Takal server, which is the one place
 * they live, and written in here on the way out.
 *
 * NOTHING SECRET PASSES THROUGH. These are Firebase's web settings, which are
 * sent to every visitor of every site that uses Firebase. The real key stays
 * on the server and is never part of this.
 */
// The same fallback as every other file in the panel. This one is fetched by
// the SERVER, so the browser's security header does not apply to it - but one
// address written two ways is how the two come to disagree, and the half that
// runs in the browser fails silently when they do.
const API =
  process.env.NEXT_PUBLIC_API_URL || "https://swat-delivery-api.onrender.com";

/** A worker that does nothing, for when Takal has no alert settings yet.
 *  It must still be valid JavaScript: a 404 or a broken file makes the browser
 *  report "registration failed", which reads as a bug rather than as "not set
 *  up yet". */
const DOES_NOTHING = `// Takal support alerts are not set up yet.
// This file is deliberately empty and valid. Nothing is broken.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil(self.clients.claim()));
`;

/**
 * The Firebase version this worker loads from Google.
 *
 * IT MUST MATCH THE ONE IN package.json. The page and the worker are two halves
 * of one conversation - the page asks for this device's alert address, the
 * worker receives what is sent to it - and two different versions of the same
 * library have disagreed about the shape of that address before. There is a
 * test that holds these two numbers together: see tests/support-alerts.test.ts.
 */
const FIREBASE_VERSION = "10.14.1";

export const dynamic = "force-dynamic";

export async function GET() {
  let cfg: Record<string, string> | null = null;
  try {
    const r = await fetch(`${API}/push-config`, { cache: "no-store" });
    if (r.ok) {
      const c = await r.json();
      if (c?.ready) cfg = c;
    }
  } catch {
    /* The panel must still load when the server is asleep. */
  }


  const body = cfg
    ? `// Generated by the panel. Do not edit: edit the settings on the server.
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-messaging-compat.js");

firebase.initializeApp({
  apiKey: ${JSON.stringify(cfg.apiKey)},
  projectId: ${JSON.stringify(cfg.projectId)},
  messagingSenderId: ${JSON.stringify(cfg.messagingSenderId)},
  appId: ${JSON.stringify(cfg.appId)}
});

const messaging = firebase.messaging();

// WHEN THE PANEL IS CLOSED. Firebase shows the alert itself when the message
// carries a notification block, which the server always sends - so this only
// adds the tap behaviour.
self.addEventListener("notificationclick", (event) => {
  const data = (event.notification && event.notification.data) || {};
  const link =
    (data.FCM_MSG && data.FCM_MSG.notification && data.FCM_MSG.notification.click_action) ||
    data.link ||
    "/dashboard/support";
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((tabs) => {
      // Re-use a panel tab that is already open rather than opening a fifth
      // one. Somebody answering support all evening should not end the evening
      // with twenty tabs.
      for (const tab of tabs) {
        if (tab.url.indexOf("/dashboard") !== -1 && "focus" in tab) {
          tab.navigate ? tab.navigate(link) : null;
          return tab.focus();
        }
      }
      return self.clients.openWindow(link);
    })
  );
});
`
    : DOES_NOTHING;

  return new Response(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // Never cached. The settings can be filled in at any moment, and a
      // browser holding yesterday's empty worker would stay silent for days.
      "Cache-Control": "no-store, max-age=0",
      "Service-Worker-Allowed": "/",
    },
  });
}
